export const ADD_CONTACT = "ADD_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";

export const REQUEST_CONTACT_LIST = "REQUEST_CONTACT_LIST";
export const SUCCESS_CONTACT_LIST = "SUCCESS_CONTACT_LIST";
export const ERROR_CONTACT_LIST = "ERROR_CONTACT_LIST";